# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://jideguru.github.io/
baseurl: 
title: JideGuru
author: Olusegun Festus Babajide
description: Personal blog and resume
about: <h3>I'm <strong>{{ site.author }}</strong>, a Fullstack developer.</h3>
	  <h3>I code for various platforms including Android, iOS and Web.</h3>
	  <h3>Have a look at some of my working <a href="{{ site.baseurl }}projects.html"> projects</a>.</h3>
	  <h3>For more check out my academic &amp; professional <a href="{{ site.baseurl }}resume">Resume</a>.</h3>
	  <h3>Contact me at <a href="http://twitter.com/{{ site.twitter }}">@{{ site.twitter }}</a> or by <a href="mailto:{{ site.email }}">email</a>.</h3>
keywords: jideguru, jide, guru
avatar: profile.png
email: guruliciousjide@gmail.com
github: jideguru # username
twitter: iamjideguru
linkedin: jideguru
stackoverflow: users/10835183/jideguru-theprogrammer  #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: jideguru
whatsapp: 22994684468
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
